Repository owencooke/memento, pull requests merged in 2025-04, with the labels that each got.

#320 Filter Memento by Image Classification
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/components/inputs/FilterMementoSheet.tsx
  app/src/hooks/useImageLables.ts
  app/src/hooks/useMementos.ts
  backend/server/api/memento/models.py
  backend/server/api/memento/views.py
  backend/server/services/db/models/joins.py
  backend/server/services/db/queries/memento.py
Labels: Functional Requirement

#322 Branding!
  .gitignore
  app/app.config.js
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/collection/create.tsx
  app/src/app/(app)/(screens)/collection/edit/[id].tsx
  app/src/app/(app)/(screens)/collection/select_mementos.tsx
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/app/(app)/(screens)/memento/create/single.tsx
  app/src/app/(app)/(screens)/memento/edit/[id].tsx
  app/src/app/(app)/(screens)/new-user.tsx
  app/src/app/(app)/(tabs)/_layout.tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/app/_layout.tsx
  app/src/app/index.tsx
  app/src/assets/fonts/Pacifico-Regular.ttf
  app/src/assets/fonts/Quicksand-Regular.ttf
  app/src/assets/images/adaptive-icon.png
  app/src/assets/images/icon.png
  app/src/assets/images/logo-android.png
  app/src/assets/images/logo-sad.png
  app/src/assets/images/logo.png
  app/src/assets/images/partial-react-logo.png
  app/src/assets/images/react-logo.png
  app/src/assets/images/react-logo@2x.png
  app/src/assets/images/react-logo@3x.png
  app/src/assets/images/splash-icon.png
  app/src/components/MementoLogo.tsx
  app/src/components/cards/MementoCard.tsx
  app/src/components/forms/CollectionForm.tsx
  app/src/components/lists/MementoGrid.tsx
  app/src/components/navigation/Header.tsx
  app/src/components/ui/IconSymbol.ios.tsx
  app/src/components/ui/IconSymbol.tsx
  app/src/components/ui/gluestack-ui-provider/config.ts
  app/src/components/ui/image/index.tsx
  app/src/libs/notifications.ts
  app/src/libs/photos.ts
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  backend/server/api/collection/views.py
  backend/server/api/image/views.py
  backend/server/api/memento/views.py
  backend/server/services/db/queries/collection.py
  backend/server/services/db/queries/image.py
  backend/server/services/process_image/converters.py
  backend/server/services/process_image/image_class.py
  backend/server/services/storage/image.py
Labels: bug

#314 Special Day Reminders (Birthday)
  .gitignore
  app/app.config.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/memento/create.tsx
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/app/(app)/(screens)/memento/create/single.tsx
  app/src/app/(app)/(screens)/new-user.tsx
  app/src/app/(app)/(tabs)/_layout.tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/app/(app)/_layout.tsx
  app/src/app/_layout.tsx
  app/src/app/index.tsx
  app/src/assets/fonts/Pacifico-Regular.ttf
  app/src/assets/fonts/Quicksand-Regular.ttf
  app/src/assets/images/adaptive-icon.png
  app/src/assets/images/google-logo.png
  app/src/assets/images/icon.png
  app/src/assets/images/logo-android.png
  app/src/assets/images/logo-sad.png
  app/src/assets/images/logo.png
  app/src/assets/images/partial-react-logo.png
  app/src/assets/images/react-logo.png
  app/src/assets/images/react-logo@2x.png
  app/src/assets/images/react-logo@3x.png
  app/src/assets/images/splash-icon.png
  app/src/components/MementoLogo.tsx
  app/src/components/lists/MementoGrid.tsx
  app/src/components/navigation/Header.tsx
  app/src/components/ui/IconSymbol.ios.tsx
  app/src/components/ui/IconSymbol.tsx
  app/src/components/ui/gluestack-ui-provider/config.ts
  app/src/components/ui/image/index.tsx
  app/src/context/AuthContext.tsx
  app/src/libs/notifications.ts
  app/src/libs/photos.ts
  backend/server/api/user/views.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/user.py
Labels: Functional Requirement

#318 Auto derive collection metadata
  app/package.json
  app/pnpm-lock.yaml
  app/src/app/(app)/(screens)/collection/select_mementos.tsx
  app/src/components/forms/CollectionForm.tsx
  app/src/components/inputs/GroupedPhotoGrid.tsx
  app/src/components/modals/AutofillFieldsModal.tsx
  app/src/components/ui/checkbox/index.tsx
  app/src/libs/metadata.ts
  backend/server/api/collection/views.py
  backend/server/services/db/queries/collection.py
Labels: Functional Requirement

#321 Delete Memento
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/components/modals/DeleteModal.tsx
  backend/server/api/memento/views.py
  backend/server/services/db/queries/memento.py
Labels: Functional Requirement

#313 Backend/Python Unit Tests + HTML Coverage Report
  .gitignore
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/components/modals/DeleteModal.tsx
  app/src/libs/notifications.ts
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  backend/server/api/memento/views.py
  backend/server/services/db/__init__.py
  backend/server/services/db/config.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/collection.py
  backend/server/services/db/queries/image.py
  backend/server/services/db/queries/memento.py
  backend/server/services/db/queries/user.py
  backend/server/services/storage/image.py
  backend/tests/README.md
  backend/tests/conftest.py
  backend/tests/db/test_image.py
  backend/tests/db/test_memento.py
  backend/tests/db/test_storage.py
  backend/tests/db/test_user.py
  backend/tests/fixtures/collection.py
  backend/tests/fixtures/file.py
  backend/tests/fixtures/image.py
  backend/tests/fixtures/memento.py
  backend/tests/fixtures/supabase.py
  backend/tests/process_image/test_background.py
  backend/tests/process_image/test_collage.py
  backend/tests/process_image/test_converters.py
  backend/tests/test_base.py
Labels: testing

#326 Jest Unit Tests + Coverage Report
  app/.gitignore
  app/README.md
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/memento.ts
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/components/cards/InteractivePhotoCard.tsx
  app/src/context/PhotoContext.tsx
  app/src/libs/metadata.ts
  app/src/libs/notifications.ts
  app/src/libs/photos.ts
  app/src/libs/string.ts
  app/tests/e2e/bulk-create.yml
  app/tests/e2e/create-memento.yml
  app/tests/e2e/edit-memento.yml
  app/tests/e2e/util/assets/tree.jpg
  app/tests/e2e/util/launch.yml
  app/tests/e2e/view-memento.yml
  app/tests/unit/README.md
  app/tests/unit/date.test.ts
  app/tests/unit/metadata.test.ts
  app/tests/unit/mocks/date.mock.ts
  app/tests/unit/mocks/libs.mock.ts
  app/tests/unit/mocks/libs.ts
  app/tests/unit/mocks/metadata.mock.ts
  app/tests/unit/notifications.test.ts
  app/tests/unit/photos.test.ts
  app/tests/unit/string.test.ts
Labels: testing

#317 System Recommended Collections
  app/src/api-client/config.ts
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/app/(app)/_layout.tsx
  app/src/app/_layout.tsx
  app/src/components/lists/MementoGrid.tsx
  app/src/hooks/useNotificationObserver.ts
  app/src/hooks/useWebSocket.ts
  backend/poetry.lock
  backend/pyproject.toml
  backend/server/api/memento/models.py
  backend/server/api/memento/views.py
  backend/server/api/router.py
  backend/server/api/testing/views.py
  backend/server/api/websocket/__init__.py
  backend/server/api/websocket/manager.py
  backend/server/api/websocket/models.py
  backend/server/api/websocket/views.py
  backend/server/application.py
  backend/server/background_tasks/process_image.py
  backend/server/background_tasks/recommend.py
  backend/server/config/openapi.py
  backend/server/services/cluster_memento/hdbscan.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/clustering.py
  backend/server/services/db/queries/memento.py
Labels: Functional Requirement

#329 Mahmud's E2E Tests
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/collection/collage/[id].tsx
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/app/(app)/(tabs)/_layout.tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/components/cards/CollectionCard.tsx
  app/src/components/cards/MementoCard.tsx
  app/src/components/modals/DeleteModal.tsx
  app/tests/e2e/delete-memento.yml
  app/tests/e2e/generate-collage.yml
  app/tests/e2e/share-memento.yml
  app/tests/e2e/util/assert-share.yml
  app/tests/e2e/util/launch.yml
  app/tests/e2e/view-map.yml
  app/tests/e2e/view-memento.yml
Labels: testing
