Repository owencooke/memento, pull requests merged in 2025-03, with the labels that each got.

#284 Create Keepsake + Extract Metadata
  .github/pull_request_template.md
  .openapi/openapi.json
  app/.gitignore
  app/README.md
  app/openapi-ts.config.ts
  app/package.json
  app/pnpm-lock.yaml
  app/scripts/sync-api.sh
  app/src/api-client/formData.ts
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/(memento)/create.tsx
  app/src/app/(app)/(tabs)/_layout.tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/app/(app)/_layout.tsx
  app/src/app/_layout.tsx
  app/src/components/cards/MementoCard.tsx
  app/src/components/inputs/DatePickerInput.tsx
  app/src/components/inputs/LocationInput.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/components/navigation/Header.tsx
  app/src/components/ui/box/index.tsx
  app/src/components/ui/box/index.web.tsx
  app/src/components/ui/box/styles.tsx
  app/src/context/AuthContext.tsx
  app/src/libs/date.ts
  app/src/libs/metadata.ts
  app/src/libs/supabase.ts
  backend/poetry.lock
  backend/pyproject.toml
  backend/server/api/memento/__init__.py
  backend/server/api/memento/models.py
  backend/server/api/memento/views.py
  backend/server/api/monitoring/views.py
  backend/server/api/path.py
  backend/server/api/router.py
  backend/server/api/user/views.py
  backend/server/services/db/models/README.md
  backend/server/services/db/models/gis.py
  backend/server/services/db/models/joins.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/image.py
  backend/server/services/db/queries/memento.py
  backend/server/services/storage/image.py
Labels: bug, Functional Requirement

#289 Manual Collection Creation
  app/.gitignore
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/(collection)/create.tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/components/cards/CollectionCard.tsx
  app/src/components/ui/alert/index.tsx
  app/src/components/ui/hstack/index.tsx
  app/src/components/ui/hstack/index.web.tsx
  app/src/components/ui/hstack/styles.tsx
  app/src/components/ui/pressable/index.tsx
  app/src/components/ui/vstack/index.tsx
  app/src/components/ui/vstack/index.web.tsx
  app/src/components/ui/vstack/styles.tsx
  backend/server/api/collection/__init__.py
  backend/server/api/collection/models.py
  backend/server/api/collection/views.py
  backend/server/api/router.py
  backend/server/api/user/views.py
  backend/server/services/db/models/joins.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/collection.py
  backend/server/services/db/queries/user.py
Labels: Functional Requirement

#294 View Collections + Edit Collections + Delete Collection
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/(collection)/[id].tsx
  app/src/app/(app)/(screens)/(collection)/create.tsx
  app/src/app/(app)/(screens)/(collection)/edit/[id].tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/components/forms/CollectionForm.tsx
  app/src/components/modals/DeleteModal.tsx
  backend/server/api/collection/models.py
  backend/server/api/collection/views.py
  backend/server/services/db/models/schema_public_latest.py
  backend/server/services/db/queries/collection.py
Labels: Functional Requirement

#293 Remove background for uploaded images
  .github/pull_request_template.md
  app/.env.sample
  app/README.md
  app/scripts/tunnel-api.sh
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/components/forms/BackgroundRemovalModal.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/hooks/usePhotos.ts
  app/src/libs/blob.ts
  backend/scripts/card.webp
  backend/scripts/test_rembg.py
  backend/server/api/image/__init__.py
  backend/server/api/image/views.py
  backend/server/api/router.py
  backend/server/services/process_image/background.py
  backend/server/services/process_image/converters.py
Labels: Functional Requirement

#295 Bulk Create Keepsakes
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/api-client/memento.ts
  app/src/app/(app)/(screens)/(memento)/create/bulk.tsx
  app/src/app/(app)/(screens)/(memento)/create/index.tsx
  app/src/app/(app)/(screens)/(memento)/edit/[id].tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/components/cards/InteractivePhotoCard.tsx
  app/src/components/draggable-grid/README.md
  app/src/components/draggable-grid/block.tsx
  app/src/components/draggable-grid/draggable-grid.tsx
  app/src/components/draggable-grid/index.ts
  app/src/components/draggable-grid/utils.ts
  app/src/components/forms/BulkCreateCollectionModal.tsx
  app/src/components/forms/MementoForm.tsx
  app/src/components/inputs/GroupedPhotoGrid.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/components/inputs/PhotoSourceSheet.tsx
  app/src/hooks/usePhotos.ts
  backend/server/api/memento/models.py
  backend/server/api/memento/views.py
Labels: Functional Requirement

#301 Map features
  app/README.md
  app/app.config.js
  app/app.json
  app/package.json
  app/src/api-client/config.ts
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/collection/create.tsx
  app/src/app/(app)/(screens)/collection/edit/[id].tsx
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/app/(app)/(screens)/memento/create/index.tsx
  app/src/app/(app)/(screens)/memento/edit/[id].tsx
  app/src/app/(app)/(tabs)/collections.tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/app/(app)/_layout.tsx
  app/src/app/+not-found.tsx
  app/src/app/_layout.tsx
  app/src/app/index.tsx
  app/src/components/cards/CollectionCard.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/components/modals/BackgroundRemovalModal.tsx
  app/src/components/modals/BulkCreateCollectionModal.tsx
  app/src/context/AuthContext.tsx
  app/src/hooks/useMementos.ts
  app/src/hooks/usePhotos.ts
  app/src/libs/date.ts
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  backend/scripts/commands.py
  backend/server/api/memento/views.py
  backend/server/services/db/models/gis.py
  backend/server/services/storage/image.py
Labels: bug, Functional Requirement

#307 Generate Collage + Sharing Memento/Collage
  app/package.json
  app/pnpm-lock.yaml
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/collection/collage/[id].tsx
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/hooks/usePhotos.ts
  app/src/libs/blob.ts
  app/src/libs/metadata.ts
  app/src/libs/string.ts
  backend/README.md
  backend/pyproject.toml
  backend/server/api/collection/views.py
  backend/server/api/router.py
  backend/server/api/testing/__init__.py
  backend/server/api/testing/views.py
  backend/server/assets/fonts/Pacifico-Regular.ttf
  backend/server/assets/fonts/Quicksand-Regular.ttf
  backend/server/config/settings.py
  backend/server/config/types.py
  backend/server/services/db/models/schema_public.sql
  backend/server/services/db/queries/collection.py
  backend/server/services/process_image/collage/README.md
  backend/server/services/process_image/collage/generator.py
  backend/server/services/process_image/collage/image_processor.py
  backend/server/services/process_image/collage/text_manager.py
  backend/server/services/storage/image.py
Labels: Functional Requirement

#312 FR-5: Display reference square overlay for camera
  app/src/api-client/memento.ts
  app/src/app/(app)/(screens)/memento/create/bulk.tsx
  app/src/app/(app)/(screens)/memento/edit/[id].tsx
  app/src/app/_layout.tsx
  app/src/components/cards/InteractivePhotoCard.tsx
  app/src/components/forms/MementoForm.tsx
  app/src/components/inputs/GroupedPhotoGrid.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/components/inputs/PhotoSourceSheet.tsx
  app/src/components/modals/BackgroundRemovalModal.tsx
  app/src/context/PhotoContext.tsx
  app/src/hooks/usePhotos.ts
  app/src/libs/blob.ts
  app/src/libs/metadata.ts
  app/src/libs/photos.ts
Labels: Functional Requirement

#311 Start of E2E testing suite via Maestro
  app/.env.sample
  app/README.md
  app/config.yaml
  app/package.json
  app/src/api-client/memento.ts
  app/src/app/(app)/(screens)/collection/collage/[id].tsx
  app/src/app/(app)/(screens)/memento/[id].tsx
  app/src/app/(app)/(screens)/memento/edit/[id].tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/components/cards/InteractivePhotoCard.tsx
  app/src/components/cards/MementoCard.tsx
  app/src/components/forms/MementoForm.tsx
  app/src/components/inputs/DatePickerInput.tsx
  app/src/components/inputs/LocationInput.tsx
  app/src/components/inputs/PhotoSelectGrid.tsx
  app/src/components/modals/BackgroundRemovalModal.tsx
  app/src/components/modals/BulkCreateCollectionModal.tsx
  app/src/components/navigation/Header.tsx
  app/src/context/AuthContext.tsx
  app/src/hooks/useMementos.ts
  app/src/libs/date.ts
  app/tests/e2e/bulk-create.yml
  app/tests/e2e/create-memento.yml
  app/tests/e2e/edit-memento.yml
  app/tests/e2e/home.yml
  app/tests/e2e/util/launch.yml
  app/tests/e2e/util/memento-form.yml
  app/tests/e2e/view-memento.yml
Labels: testing

#300 FR-41 Add Keepsakes
  app/src/app/(app)/(screens)/collection/[id].tsx
  app/src/app/(app)/(screens)/collection/create.tsx
  app/src/app/(app)/(screens)/collection/edit/[id].tsx
  app/src/app/(app)/(screens)/collection/select_mementos.tsx
  app/src/app/(app)/(screens)/memento/create/index.tsx
  app/src/app/(app)/(screens)/memento/edit/[id].tsx
  app/src/app/(app)/(tabs)/mementos.tsx
  app/src/components/cards/MementoCard.tsx
  app/src/components/forms/CollectionForm.tsx
  app/src/components/lists/MementoGrid.tsx
  backend/server/api/collection/views.py
  backend/server/services/db/queries/collection.py
Labels: Functional Requirement

#315 OCR + Image Classification
  app/src/api-client/generated/@tanstack/react-query.gen.ts
  app/src/api-client/generated/sdk.gen.ts
  app/src/api-client/generated/types.gen.ts
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  backend/server/api/image/views.py
  backend/server/api/memento/views.py
  backend/server/services/db/queries/image.py
  backend/server/services/process_image/converters.py
  backend/server/services/process_image/image_class.py
  backend/server/services/storage/image.py
Labels: Functional Requirement
